### ISSUE TITLE
Unable to use negative lookahead in regex search

### ISSUE THREAD

**Issue by byronaltice** [bibixx/tab-pinner#13]
Example regex:

`^http[s]?://nsconline-my.sharepoint.com/personal/my_name/(?!_)*`

This matches:

https://nsconline-my-sharepoint.com/personal/my_name/_layouts/

but it should only match anything without an underscore after `my_name/`

**Comment by bibixx** [comment]
@byronaltice I think this isn't necessarily a problem with tab pinner, but more of a problem with regex 😉

You can see that your regex matches the start of the url and because of that the whole url is being matched
![image](https://user-images.githubusercontent.com/14880213/109862878-41a5f800-7c61-11eb-806a-eb90dfa7eaf8.png)
_https://regexr.com/5np57_

To be honest I'm not too familiar with negative lookaheads, but this seems to fix it (notice the lack of `*` at the end) 
```
^http[s]?://nsconline-my.sharepoint.com/personal/my_name/(?!_)
```
![image](https://user-images.githubusercontent.com/14880213/109863059-787c0e00-7c61-11eb-9d23-fbeddb04b022.png)
_https://regexr.com/5np5d_

If I were to do it personally I'd do it this way (the `\n` in the ss is only to handle multiline matching in regexr)
```
^http[s]?://nsconline-my.sharepoint.com/personal/my_name/[^_]*$
```
![image](https://user-images.githubusercontent.com/14880213/109863283-be38d680-7c61-11eb-89cc-1e95e612454e.png)
_https://regexr.com/5np5m_

Or if you wanted to match only the folder inside `my_name` (and not the folder itself) then you could use this
```
^http[s]?://nsconline-my.sharepoint.com/personal/my_name/[^_]+$
```
![image](https://user-images.githubusercontent.com/14880213/109863711-41f2c300-7c62-11eb-91e7-8129cdfde4bd.png)
_https://regexr.com/5np5p_
